all:
	cd command;make;cd ..
	cd common;make;cd ..
	cd task;make;cd ..
	cd thread;make;cd ..
	cd main;make;cd ..
install:
	cd command;make install;cd ..
	cd common;make install;cd ..
	cd task;make install;cd ..
	cd thread;make install;cd ..
	cd main;make install;cd ..
clean:
	make -f makeobj clean;
	cd command;make clean;cd ..
	cd common;make clean;cd ..
	cd task;make clean;cd ..
	cd thread;make clean;cd ..
	cd main;make clean;cd ..
