#ifndef __FRAMECOMMON_H
#define __FRAMECOMMON_H
#include "AES.h"
#include "Config.h"
#include "buffermgr.h"
#include "cmysql.h"
#include "commondef.h"
#include "csha1.h"
#include "hashfile.h"
#include "httpsocket.h"
#include "iparea.h"
#include "myexception.h"
#include "myfile.h"
#include "mymd5.h"
#include "mysocket.h"
#include "sendmailclient.h"
#include "snappage.h"
#include "threadmutex.h"
#include "toolkit.h"
#include "writeRunInfo.h"
#include "httptools.h"
#include "pidlist.h"
#include "urlencrypt.h"
#include "threadrwlock.h"
#include "myhashtable.h"
#include "PipeInterrupter.h"
#include "SyncWrapper.h"
#include "AsyncQueue.h"
#include "BufferHelper.h"
#include "CommonFun.h"
#include "CommonDef2.h"
#include "MysqlWrapper.h"
#include "mylist.h"
#include "mod_h264_streaming.h"
#include "moov.h"
#include "RSA.h"
#include "mhxy_udp.h"
#include "AESEncryptApplication.h"
#include "decompress.h"
#include "udpcommonsock.h"
#include "safe_thread_list.h" //added by dijie 09-11-2
#include "localdomainparser.h" //added by hanzhiliang 10-04-14
#include "bencoding.h"
#include "atomic32.h"
#endif

