INCLUDE=-I/usr/include/mysql/ -I$(FRAMECOMMON)/include
LIBS=-L$(FRAMECOMMON)/lib -lframecommon /usr/lib64/mysql/libmysqlclient_r.a -lz -pthread -lssl -luuid 
CFLAGS = -g -Wall -fPIC

all:$(BINARY)

$(BINARY):$(FILENAME)
	 $(CXX) $< -o $@  $(INCLUDE) $(LIBS) $(CFLAGS) 
